apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spicedb-instance.fullname" . }}
stringData:
  preshared_key: {{ .Values.spicedb.presharedKey }}
---
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: {{ include "spicedb-instance.fullname" . }}
spec:
  config:
    dashboardEnabled: True
    datastoreEngine: memory
  secretName: {{ include "spicedb-instance.fullname" . }}